default:VirtualEnvironment/VirtualEnvironment.java GateManager/GateManager.java 
	javac -d ../classes/ -J-Dfile.encoding=UTF8 GateManager/*.java
	javac -d ../classes/ -J-Dfile.encoding=UTF8 VirtualEnvironment/VirtualEnvironment.java
