default:VirtualMachine/VirtualMachine.java GateManager/GateManager.java 
	javac -d ../classes/ -J-Dfile.encoding=UTF8 GateManager/GateManager.java
	javac -d ../classes/ -J-Dfile.encoding=UTF8 VirtualMachine/VirtualMachine.java
